sudo: required
services:
  - docker

before_install:
  - docker build -t seongbo5230/docker-k8s -f Dockerfile.dev .

script:
  - docker run -e CI=true seongbo5230/docker-k8s npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-k8s"
  env: "DockerK8s-env"
  bucket_name: "elasticbeanstalk-us-west-1-946811956022"
  bucket_path: "docker-k8s"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
